#!/bin/bash

CONFIG="$HOME/.config/hypr/modules/waybar/config"
STYLE="$HOME/.config/hypr/modules/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
	# waybar --bar main-bar --log-level error
fi
